feat: add front matter variable to open in new tab
YoussefRaafatNasry/portfolYOU pull request #81
Opened 2021-08-30 21:47 UTC by Avery2

Similar to (#77), allows links in the navbar to open in a new tab. This time it is optional with front matter `open_new_tab`.

Example:
```
---
title: <i class="fab fa-github"></i>
external_url: https://github.com/Avery2
open_new_tab: true
weight: 99
---
```

2021-08-31 11:16 UTC, YoussefRaafatNasry commented
I like this approach more, but I think that we should add it to other content that can have an external URL too, like projects and posts.

2021-08-31 11:19 UTC, YoussefRaafatNasry requested changes

2021-08-31 11:19 UTC, YoussefRaafatNasry commented on _includes/navbar.html
> +        {%- endif -%}
An inline if statement would be cleaner.

```suggestion
          <a class="nav-item nav-link {{ active_status }}" href="{{ url }}" {%- if html_page.open_new_tab -%} target="_blank" {%- endif -%}>{{ html_page.title }}</a>
```

2021-08-31 12:35 UTC, YoussefRaafatNasry commented
We can make this as a site-level configuration in `_config.yaml` to make it easier to standardize the behavior across site. What do you think?

2021-08-31 15:02 UTC, Avery2 commented
> We can make this as a site-level configuration in `_config.yml` to make it easier to standardize the behavior across site.
> What do you think?

Yeah, that sounds good. I'll try to do that.

2021-09-07 01:36 UTC, Avery2 commented
> We can make this as a site-level configuration in `_config.yml` to make it easier to standardize the behavior across site.

Right now there is just a setting `open_new_tab` in `_config.yml` that affects the default behavior of the links in the navbar. I have not yet been able to implement this in the projects or posts.

2021-09-07 06:39 UTC, Avery2 commented
Works for navbar (pages), projects, and posts. Users can edit the `open_new_tab` front matter in any of the corresponding files. They also can set site-wide defaults in the `_config.yml` (default value is false - so the default behavior will remain the same). Sorry that the git history is a little horrendous, I wasn't sure how to develop locally with the `remote_theme`.

2021-09-10 01:35 UTC, YoussefRaafatNasry commented
@Avery2 the PR have irrelevant changes from your fork, consider separating them or closing the PR and creating a new one. 
Sorry for the late response.

2021-09-10 01:40 UTC, Avery2 commented
> @Avery2 the PR have irrelevant changes from your fork, consider separating them or closing the PR and creating a new one.
> Sorry for the late response.

My bad, I will change that.

2021-09-10 01:44 UTC, Avery2 commented
New PR at #82

2021-09-10 01:58 UTC, closed without merging